Add toggle to stickiness due to TF/AWS API issues
rackspace-infrastructure-automation/aws-terraform-nlb pull request #22
Opened 2020-10-06 13:31 UTC by dannyleesmith

##### Corresponding Issue(s):

N/A

##### Summary of change(s):

- make new v0.12.1 `stickiness` block a toggled option, missing by default, to allow for current AWS/TF issues

##### Reason for Change(s):

BUG: due to some issues between Terraform and the AWS API there are mixed results when creating a TCP or UDP TG that sometimes requires `stickiness` to be set in a specific way or not at all.

References:

https://github.com/terraform-providers/terraform-provider-aws/issues/9093#issuecomment-696830753
https://github.com/terraform-providers/terraform-provider-aws/pull/15295

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:

Believe not

##### Does this update/change involve issues with other external modules? If so, please describe the scenario.

No

##### If input variables or output variables have changed or has been added, have you updated the README?

Yes

##### Do examples need to be updated based on changes?

No

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

2020-10-09 18:06 UTC, johnctitus requested changes
I think we might need to implement the change to the TG Map within our test deployment.  Although the test "passed" it looks like the update generated that error.

2020-10-26 08:33 UTC, dannyleesmith commented
@johnctitus I think that's the tests satisfactorily resolved now, thanks

2020-10-26 15:49 UTC, johnctitus approved these changes
Looks much better now.  👍

2020-10-26 15:56 UTC, twistedgrim approved these changes

2020-10-26 16:23 UTC, merged